class Recipe {
  final int id;
  final String title;
  final String servings;
  final String time;
  final String description;
  final String imageAsset;
  final String iconImage; 
  final bool isVegetarian;
  final bool isComplicated;
  final String season;
  bool isFavourite; 
  final Map<String, List<String>> ingredients;
  final Map<String, List<String>> method;
  final List<Recipe> subRecipes;

  Recipe({
    required this.id,
    required this.title,
    required this.servings,
    required this.time,
    required this.description,
    required this.imageAsset,
    required this.iconImage,
    required this.isVegetarian,
    required this.isComplicated,
    required this.season,
    this.isFavourite = false,
    required this.ingredients,
    required this.method,
    this.subRecipes = const [],
  });
}

// Sample recipes
final List<Recipe> allRecipes = [
  Recipe(
    id: 1,
    title: 'Complete Breakfast',
    servings: '4 servings',
    time: '45 minutes',
    description: "You'll feel ready to take on the world! This highly nutritious meal is a farmer's best friend.",
    imageAsset: 'assets/images/completeBreakfast.jpg', 
    iconImage: 'assets/images/completeBreakfastIcon.png', 
    isVegetarian: true,
    isComplicated: true,
    season: 'Spring',
    isFavourite: false,
    ingredients: {
      'Fried Egg': ['2 tbsp EXTRA_VIRGIN OLIVE OIL', '1 tbs UNSALTED BUTTER', '8 LARGE EGGS', 'KOSHER SALT', 'FRESHLY GROUND BLACK PEPPER'],
      'Hash Browns': ['1 RUSSET POTATOES', '2 tbsp CORNSTARCH', '1 tsp GRANULATED GARLIC', '1/2 tsp ONION POWDER', 'FRESHLY GROUND BLACK PEPPER', 'NEUTRAL HIGH_HEAT COOKING OIL', 'KOSHER SALT'],
      'Yogurt Pancakes': ['8 oz FRESH RHUBARD', '50g GRANULATED SUGAR', '3 tbsp WATER', 'KOSHER SALT', '115g fresh SALMONBERRIES', '210g ALL-PURPOSE FLOUR', '1 tbsp BAKING SODA', '1.5 tbsp BAKING POWDER', '2 LARGE EGGS, at room temp', '2 tbsp HONEY', '300g PLAIN FULL_FAT GOAT"S MILK COW\'s MILK YOGURT', '2 tbsp UNSALTED BUTTER',],
    },
    method: {
      'Fried Egg': ['Heat oil in a pan.', 'Crack the egg and fry until the whites are set.'],
      'Hash Browns': ['Preheat the oven to 200°F(95°C).', 'Fit a rimmed baking sheet with a wire rack.', 'Grate the potato.', 'Fry in a hot oiled pan until crispy and golden brown.'],
      'Yogurt Pancakes': ['Mix flour, egg, and yogurt.', 'Pour batter onto a hot griddle and flip when bubbly.'],
    },
  ),
  Recipe(
    id: 2,
    title: 'Farmer\'s Lunch',
    servings: '1 serving',
    time: '60 minutes',
    description: "There's little heart candies on top. I'm sure you'll fall in love with it.",
    imageAsset: 'assets/images/farmerLunch.jpg', // Real photo
    iconImage: 'assets/images/farmerLunchIcon.png', // Stardew icon
    isVegetarian: true,
    isComplicated: false, // Simple dish
    season: 'Spring',
    isFavourite: true,
    ingredients: {
      'Main': [
        '3 LARGE EGGS',
        '2 tbsp WHOLE MILK',
        '1 tbsp UNSALTED BUTTER',
        'KOSHER SALT',
        'FRESHLY GROUND BLACK PEPPER',
        '1/2 cups grated GRUYERE CHEESE',
        '2 tbsp coarsely chopped FRESH SPRING HERBS (chervil, tarragon, chives, parsley)',
        'ROASTED PARSNIPS WITH BABY ARUGULA',
      ],
    },
    method: {
      'Main': [
        'Separate the egg whites and egg yolks.',
        'Whip the egg whites until they form medium-stiff peaks. (2mins)',
        'Drizzle the milk over the egg yolks.',
        'Use mixer to whip the yolkq until the mixture is slightly airy and pale yellow. (2mins)',
        'Gently fold the yolks into the whites until just combined.',
        'Heat a medium cast-iron skillet over medium-low heat.',
        'Add the butter to the warm skillet and swirl to coat the bottom.',
        'Carefully pour the egg mixture into the skillet and cook until the bottom are set. (6-8mins)',
        'Cover the skillet with a lid and cook until the top is mostly set. (4-6mins)',
        'Season the eggs with salt and pepper, and sprinkle with the cheese.',
        'Cover the skillet again and cook until the cheese is melted. (2mins)',
        'Sprinkle the eggs with the herbs',
        'Use a rubber spatula to loosen the side of the omelet, then fold the omelet over.',
        'Switch to a wide metal spatula to carefully transfer the omelet to a plate.',
        'Serve immediately, along with a few large spoonfuls of the parsnips.',
      ],
    },
    subRecipes: [
      Recipe(
        id: 101, 
        title: 'ROASTED PARSNIPS with BABY ARUGULA',
        servings: '4 serving',
        time: '60 minutes',
        description: "There's little heart candies on top. I'm sure you'll fall in love with it.",
        imageAsset: 'assets/images/parsnips.png', 
        iconImage: 'assets/images/image_29c1a5.png', 
        isVegetarian: true,
        isComplicated: false, 
        season: 'Spring',
        isFavourite: true,
        ingredients: {
          'Main': [
            '450g fresh parsnips, peeled and cut into 1/2-inch pieces',
            '2 tbsp extra-virgin olive oil',
            '1 tbsp maple syrup',
            'KOSHER SALT',
          ],
        },
        method: {
          'Main': [
            'Preheat the oven to 375°F (190°C).',
            'Toss the parsnips with the olive oil, maple syrup, and salt.',
            'Spread the parsnips on a baking sheet and roast for 25-30 minutes, until tender and lightly browned.',
            'Let cool for a few minutes before serving with baby arugula.',
          ],
        },
      ),
    ],
  ),
  Recipe(
    id: 3,
    title: 'Vegetable Stock',
    servings: '2 quarts',
    time: '15 minutes',
    description: "There's little heart candies on top. I'm sure you'll fall in love with it.",
    imageAsset: 'assets/images/vegetableStockLong.jpg', 
    iconImage: 'assets/images/vegeStockIcon.png', 
    isVegetarian: true,
    isComplicated: false, 
    season: 'Spring',
    isFavourite: false,
    ingredients: {
      'Main': [
        '3 pounds VEGETABLE SCRAPS',
        '2 BAY LEAVES',
        '1 tbsp BLACK PEPPERCORN',
        '12 cups WATER',
      ],
    },
    method: {
      'Main': [
        'Place the vegetable scraps in a large pot and cover with water.',
        'Add the bay leaves and black peppercorns.',
        'Bring the mixture to a boil, then reduce the heat and simmer for 1-2 hours, or until the stock is rich and flavorful.',
        'Strain the stock through a fine-mesh sieve into a clean container.',
        'Let the stock cool before transferring it to storage containers in the refrigerator or freezer.',
      ],
    },
  ),
  Recipe(
    id: 4,
    title: 'Bread and Bruschetta',
    servings: '4 servings',
    time: '40 minutes',
    description: "Nothing says summer quite like a fresh, juicy tomato.",
    imageAsset: 'assets/images/bread&bruschetta.jpg', 
    iconImage: 'assets/images/bread&bruschettaIcon.png', 
    isVegetarian: true,
    isComplicated: true,
    season: 'Summer',
    isFavourite: false,
    ingredients: {
      'Bread': [
        '315ml lukewarm WATER', 
        '2 tbs HONEY', 
        '1.5 tbs active dry YEAST', 
        '350g all-purpose FLOUR', 
        '105g whole wheat FLOUR',
        'KOSHER SALT',
        '395ml WATER',
        'EXTRA-VIRGIN OLIVE OIL',
      ],
      'Bruschetta': [
        '450g RIPE TOMATOES', 
        '75ml EXTRA-VIRGIN OLIVE OIL', 
        '1.5 tsp RED WINE VINEGAR', 
        '2 BREAD BAGUETTES', 
        '2 large GARLIC CLOVES', 
        '4g lightly packed hand-torn fresh BASIL LEAVES', 
        'flaky SEA SALT',
      ],
    },
    method: {
      'Bread': [
        'In a large bowl, combine the lukewarm water, honey, and yeast. Let it sit for 5-10 minutes until it becomes frothy.', 
        'Add the all-purpose flour, whole wheat flour, and kosher salt to the yeast mixture. Stir until a shaggy dough forms.',
        'Turn the dough onto a floured surface and knead for about 10 minutes until',
        'the dough is smooth and elastic. If the dough is too sticky, add a little more flour as needed.',
        'Place the dough in a lightly oiled bowl, cover it with a clean kitchen towel.',
        'Let the dough rise in a warm place for about 1 hour, or until it has doubled in size.',
        'Preheat the oven to 450°F (230°C).',
        'Punch down the risen dough and shape it into a round loaf.',
        'Place the loaf on a baking sheet lined with parchment paper.',
        'Bake for 25-30 minutes, or until the bread is golden brown and sounds hollow when tapped on the bottom.',
        'Remove the bread from the oven and let it cool on a wire rack before slicing.',
      ],
      'Bruschetta': [
        'Preheat the oven to 375°F(190°C).', 
        'Core and chop the tomatoes into small pieces and place them in a bowl.', 
        'Add the olive oil, red wine vinegar, and garlic to the tomatoes.', 
        'Season with salt and pepper to taste, and stir to combine. Let the mixture sit for at least 10 minutes to allow the flavors to meld.',
        'Slice the baguettes into 1/2-inch thick slices and place them on a baking sheet.',
        'Toast the bread in the preheated oven for about 5-7 minutes, or until the bread is golden and crispy.',
        'Remove the toasted bread from the oven and rub each slice with a cut garlic clove for extra flavor.',
        'Top each slice of toasted bread with a spoonful of the tomato mixture.',
        'Garnish with fresh basil leaves and a sprinkle of flaky sea salt.',
        'Serve immediately and enjoy your delicious bruschetta!',
      ],
    },
  ),
  Recipe(
    id: 5, 
    title: 'Maki Roll',
    servings: '6 serving',
    time: '60 minutes',
    description: "Dip each piece in soy sauce with a bit of wasabi, and you're in for a treat!",
    imageAsset: 'assets/images/makiRoll.jpg', 
    iconImage: 'assets/images/makiRollIcon.png', 
    isVegetarian: false,
    isComplicated: false, 
    season: 'Summer',
    isFavourite: false,
    ingredients: {
      'Main': [
        '1.5 cups good-quality JAPANESE SHORT-GRAIN RICE',
        '1.5 cups WATER',
        '0.5 cup finely diced CARROT',
        '0.25 cup UNSEASONED RICE WINE VINEGAR',
        '1 tbsp GRANULATED SUGAR',
        'KOSHER SALT',
        '12 ounces skinless SUSHI_GRADE SALMON FILLET',
        '3 tbsp MAYONNAISE',
        '2-3 tsp ASIAN CHILI SAUCE',
        '0.5 tsp toasted SESAME OIL',
        '2 thinly sliced SCALLIONS',
        '6 full-size ROASTED NORI SHEETS',
        '1 large PERSIAN CUCUMBER, thinly sliced into matchsticks',
        '1 ripe AVOCADO, halved, seed removed, sliced lengthwise into 18 pieces',
        'PICKLED GINGER, WASABI, and SOY SAUCE, for serving',
      ],
    },
    method: {
      'Main': [
        'Rinse the rice under cold water until the water runs clear. ',
        'Place the rinsed rice and water in a medium saucepan and let it soak for 30 minutes.',
        'Bring the mixture to a boil, then reduce the heat to low, cover, and simmer for 18-20 minutes, or until the water is absorbed and the rice is tender.',
        'Remove the saucepan from the heat and let it sit, covered, for 10 minutes.',
        'In a small bowl, whisk together the rice wine vinegar, sugar, and salt until the sugar is dissolved.',
        'Transfer the cooked rice to a large bowl and gently fold in the vinegar mixture. Let the rice cool to room temperature.',
        'In a medium bowl, combine the diced carrot, mayonnaise, chili sauce, sesame oil, and scallions. Mix well to create the spicy salmon filling.',
        'Place a nori sheet on a bamboo sushi mat, shiny side down.',
        'Spread a thin layer of the cooled rice over the nori sheet, leaving a 1-inch border at the top edge.',
        'Arrange a line of the spicy salmon filling, cucumber matchsticks, and avocado slices across the center of the rice.', 
        'Using the bamboo mat, carefully roll the sushi away from you, applying gentle pressure to create a tight roll. Seal the edge with a little water.',
        'Repeat the process with the remaining nori sheets and fillings.',
        'Use a sharp knife to slice each roll into 6-8 pieces.',
        'Serve the maki rolls with pickled ginger, wasabi, and soy sauce for dipping.',
      ],
    },
  ),
  Recipe(
    id: 6,
    title: 'Lucky Lunch',
    servings: '4 servings',
    time: '30 minutes',
    description: "If you've been on the hunt for the perfect seafood lunch, then you're in luck!",
    imageAsset: 'assets/images/luckyLunch.jpg', 
    iconImage: 'assets/images/luckyLunchIcon.png', 
    isVegetarian: false,
    isComplicated: false, 
    season: 'Summer',
    isFavourite: false,
    ingredients: {
      'Main': [
        '6 cups WATER',
        '0.5 cup FRESH LIME JUICE',
        'KOSHER SALT',
        '12 ounce large SHRIMP, peeled and deveined',
        '5 tbsp EXTRA-VIRGIN OLIVE OIL',
        '0.75 tbsp GRANULATED SUGAR',
        '2 GARLIC CLOVES, minced',
        '0.5 small RED ONION, finely chopped',
        '1 JALAPENO, seeded and thinly sliced',
        '1 large PERSIAN CUCUMBER',
        '1 cup RAINBOW CHERRY TOMATOES, quartered',
        '12 YELLOW CORN TORTILLA',
        '1 small AVOCADO, halved, pit removed, cut into 0.5-inch cubes',
        '3 tbsp thinly sliced FRESH CHIVE GREENS, plus flowers for garnish',
        '0.25 cup coarsly chopped FRESH CILANTRO LEAVES and SOFT STEMS',
        '2 packed cups thinly sliced ROMAINE LETTUCE',
      ],
    },
    method: {
      'Main': [
        'Heat the olive oil in a large skillet over medium-high heat.',
        'Add the shrimp and cook for 2-3 minutes per side, or until they turn pink and are cooked through.',
        'Remove the shrimp from the skillet and set aside.',
        'In the same skillet, add the lime juice and salt, and stir to combine.',
        'Add the garlic, red onion, jalapeño, cucumber, tomatoes, and lettuce to the skillet.',
        'Toss everything together until well combined.',
        'Return the shrimp to the skillet and toss to coat with the dressing.',
        'Serve immediately on the corn tortillas, topped with avocado cubes and fresh herbs.',
      ],
    },
  ),
  Recipe(
    id: 7,
    title: 'Pumpkin Soup',
    servings: '4 servings',
    time: '40 minutes',
    description: "Nothing says summer quite like a fresh, juicy tomato.",
    imageAsset: 'assets/images/pumpkinSoup.jpg', 
    iconImage: 'assets/images/pumpkinSoupIcon.png', 
    isVegetarian: true,
    isComplicated: false,
    season: 'Fall',
    isFavourite: false,
    ingredients: {
      'Main': [
        '1 small KABOCHA SQUASH(2.5lb)',
        '3 tbsp EXTRA-VIRGIN OLIVE OIL',
        'KOSHER SALT',
        'FRESHLY GROUND BLACK PEPPER',
        '2 tbsp UNSALTED BUTTER',
        '1 large YELLOW ONION, thinly sliced',
        '3 GARLIC CLOVES, sliced',
        '1 piece FRESH GINGER, peeled and finely chopped',
        '0.5 cup APPLE CIDER',
        '1 tbsp APPLE CIDER VINEGAR',
        '1 large branch FRESH THYME',
        '1 FRESH ROSEMSARY SPRIG',
        '2 BAY LEAVES',
        '6 cups VEGETABLE STOCK',
        '1/3 cup SOUR CREAM',
        '3-5 tbsp WHOLE MILK',
        'PECORINO FRICO',
        ],
    },
    method: {
      'Main': [
        'Preheat the oven to 400°F (200°C).',
        'Line a baking sheet with parchment paper. Cut the kabocha squash in half and scoop out the seeds.',  
        'Place the squash halves cut-side down on the prepared baking sheet. Drizzle with olive oil and season with salt and pepper.',
        'Roast the squash for 45-50 minutes, or until the flesh is tender when pierced with a fork.',
        'Remove the squash from the oven and let it cool slightly. Scoop the flesh out of the skin and set aside.',
        'In a large pot, melt the butter over medium heat. Add the onion and cook until softened, about 5 minutes.',
        'Add the garlic and ginger and cook for another 1-2 minutes, until fragrant.',
        'Pour in the apple cider and vinegar, and add the thyme, rosemary, and bay leaves. Simmer for 5 minutes to let the flavors meld.',
        'Add the roasted squash flesh and vegetable stock to the pot. Bring to a boil, then reduce the heat and simmer for 20 minutes.',
        'Remove the thyme, rosemary, and bay leaves from the soup. Use an immersion blender to puree the soup until smooth.',
        'Stir in the sour cream and milk until well combined. Season with salt and pepper to taste.',
        'Serve hot, garnished with crumbled pecorino frico.',
      ],
    },
    subRecipes: [
      Recipe(
        id: 701, 
        title: 'PECORINO FRICO',
        servings: '4 serving',
        time: '60 minutes',
        description: "There's little heart candies on top. I'm sure you'll fall in love with it.",
        imageAsset: 'assets/images/parsnips.png', 
        iconImage: 'assets/images/image_29c1a5.png', 
        isVegetarian: true,
        isComplicated: false, 
        season: 'Summer',
        isFavourite: true,
        ingredients: {
          'Main': [
            '0.5 cup PECORINO ROMANO CHEESE, finely grated',
            '2 tbsp raw pepitas',
          ],
        },
        method: {
          'Main': [
            'Line a baking sheet with parchment paper. In a small bowl, toss the grated pecorino with the pepitas.',
            'Spoon the cheese mixture onto the prepared baking sheet, forming 4-6 small mounds. Flatten each mound slightly with the back of a spoon.',
            'Bake for 5-7 minutes, or until the cheese is melted and golden brown.',
            'Remove the frico from the oven and let it cool on the baking sheet for a few minutes before transferring to a wire rack to cool completely.',  
          ],
        },
      ),
    ],
  ),
  Recipe(
    id: 8,
    title: 'Super Meal',
    servings: '4 servings',
    time: '1.15 hours',
    description: "If you've been on the hunt for the perfect seafood lunch, then you're in luck!",
    imageAsset: 'assets/images/superMeal.jpg', 
    iconImage: 'assets/images/superMealIcon.png', 
    isVegetarian: true,
    isComplicated: true, 
    season: 'Fall',
    isFavourite: false,
    ingredients: {
      'Farro': [
        '315ml lukewarm WATER', 
        '2 tbs HONEY', 
        '1.5 tbs active dry YEAST', 
        '350g all-purpose FLOUR', 
        '105g whole wheat FLOUR',
        'KOSHER SALT',
        '395ml WATER',
        'EXTRA-VIRGIN OLIVE OIL',
      ],
      'Baby Artichokes & Bok Choy': [
        '450g RIPE TOMATOES', 
        '75ml EXTRA-VIRGIN OLIVE OIL', 
        '1.5 tsp RED WINE VINEGAR', 
        '2 BREAD BAGUETTES', 
        '2 large GARLIC CLOVES', 
        '4g lightly packed hand-torn fresh BASIL LEAVES', 
        'flaky SEA SALT',
      ],
      'Avocado-Green Goddess Dressing': [
        '450g RIPE TOMATOES', 
        '75ml EXTRA-VIRGIN OLIVE OIL', 
        '1.5 tsp RED WINE VINEGAR', 
        '2 BREAD BAGUETTES', 
        '2 large GARLIC CLOVES', 
        '4g lightly packed hand-torn fresh BASIL LEAVES', 
        'flaky SEA SALT',
      ],
    },
    method: {
      'Farro': [
        'In a large bowl, combine the lukewarm water, honey, and yeast. Let it sit for 5-10 minutes until it becomes frothy.', 
        'Add the all-purpose flour, whole wheat flour, and kosher salt to the yeast mixture. Stir until a shaggy dough forms.',
        'Turn the dough onto a floured surface and knead for about 10 minutes until',
        'the dough is smooth and elastic. If the dough is too sticky, add a little more flour as needed.',
        'Place the dough in a lightly oiled bowl, cover it with a clean kitchen towel.',
        'Let the dough rise in a warm place for about 1 hour, or until it has doubled in size.',
        'Preheat the oven to 450°F (230°C).',
        'Punch down the risen dough and shape it into a round loaf.',
        'Place the loaf on a baking sheet lined with parchment paper.',
        'Bake for 25-30 minutes, or until the bread is golden brown and sounds hollow when tapped on the bottom.',
        'Remove the bread from the oven and let it cool on a wire rack before slicing.',
      ],
      'Baby Artichokes & Bok Choy': [
        'Preheat the oven to 375°F(190°C).', 
        'Core and chop the tomatoes into small pieces and place them in a bowl.', 
        'Add the olive oil, red wine vinegar, and garlic to the tomatoes.', 
        'Season with salt and pepper to taste, and stir to combine. Let the mixture sit for at least 10 minutes to allow the flavors to meld.',
        'Slice the baguettes into 1/2-inch thick slices and place them on a baking sheet.',
        'Toast the bread in the preheated oven for about 5-7 minutes, or until the bread is golden and crispy.',
        'Remove the toasted bread from the oven and rub each slice with a cut garlic clove for extra flavor.',
        'Top each slice of toasted bread with a spoonful of the tomato mixture.',
        'Garnish with fresh basil leaves and a sprinkle of flaky sea salt.',
        'Serve immediately and enjoy your delicious bruschetta!',
      ],
      'Avocado-Green Goddess Dressing': [
        'In a food processor, combine the avocado, lime juice, and garlic. Process until smooth.',
        'With the processor running, slowly drizzle in the olive oil until the dressing is well combined.',
        'Season with salt and pepper to taste.',
        'Taste and adjust the seasoning as needed.',
      ],
    },
  ),
];