// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfXFKlPpq4LlCKGC2jWLGsMNtsI7Yc1b0',
    appId: '1:709918116887:web:711bdb034c443b4f4de052',
    messagingSenderId: '709918116887',
    projectId: 'flutterfire-ui-codelab-3dc28',
    authDomain: 'flutterfire-ui-codelab-3dc28.firebaseapp.com',
    storageBucket: 'flutterfire-ui-codelab-3dc28.firebasestorage.app',
    measurementId: 'G-N8VG2SDJ6Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxgapLBlMDwd_w3VkdP033-BhRYU1AWUM',
    appId: '1:709918116887:android:cf223e84d65bc9e94de052',
    messagingSenderId: '709918116887',
    projectId: 'flutterfire-ui-codelab-3dc28',
    storageBucket: 'flutterfire-ui-codelab-3dc28.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCATqHnNY_oQ2C3uuNnmnlAGORavnjTktE',
    appId: '1:709918116887:ios:6b5d67493947cc164de052',
    messagingSenderId: '709918116887',
    projectId: 'flutterfire-ui-codelab-3dc28',
    storageBucket: 'flutterfire-ui-codelab-3dc28.firebasestorage.app',
    iosBundleId: 'com.example.recipeLayout',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCATqHnNY_oQ2C3uuNnmnlAGORavnjTktE',
    appId: '1:709918116887:ios:6b5d67493947cc164de052',
    messagingSenderId: '709918116887',
    projectId: 'flutterfire-ui-codelab-3dc28',
    storageBucket: 'flutterfire-ui-codelab-3dc28.firebasestorage.app',
    iosBundleId: 'com.example.recipeLayout',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfXFKlPpq4LlCKGC2jWLGsMNtsI7Yc1b0',
    appId: '1:709918116887:web:08eaca92e61d9abf4de052',
    messagingSenderId: '709918116887',
    projectId: 'flutterfire-ui-codelab-3dc28',
    authDomain: 'flutterfire-ui-codelab-3dc28.firebaseapp.com',
    storageBucket: 'flutterfire-ui-codelab-3dc28.firebasestorage.app',
    measurementId: 'G-J1FL49N4F0',
  );
}
